import Head from 'next/head';
import React, {useEffect} from 'react'
import ContactContainer from '../components/ContactContainer'
import LoadingBar from '../components/LoadingBar';
import BookTable from '../components/BookTable';
function showContact(){
    let contactBtn = document.getElementById("contact-btn");
    if(document.documentElement.scrollTop + window.innerHeight  >= contactBtn.offsetTop){
        contactBtn.classList.add("fade-animation")
      }
      window.addEventListener("scroll",()=>{
        if(document.documentElement.scrollTop + window.innerHeight  >= contactBtn.offsetTop){
            contactBtn.classList.add("fade-animation")
          }
      })
}
function Contact() {
    useEffect(() => {
     showContact()
    }, [])
    
  return (
    <>
    <Head>
    <title>Contact | Osteria</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href={`${process.env.NEXT_PUBLIC_IMAGESPATH}/favicon.ico`}/>
  </Head>
  <BookTable/>
  <LoadingBar/>
    <ContactContainer/>
    </>
  )
}

export default Contact